# PyTorch Basic

PyTorch 기초 사용법

In [0]:
import numpy as np
import torch

In [7]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x.ndimension()

2

In [8]:
x = torch.unsqueeze(x,0) # 랭크 늘리기
x.shape

torch.Size([1, 3, 3])

In [9]:
x = torch.squeeze(x) #랭크 줄이기
x.size()

torch.Size([3, 3])

In [16]:
x = x.view(9)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
nums = torch.arange(9)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
nums.shape

torch.Size([9])

In [0]:
type(nums)

torch.Tensor

In [0]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [0]:
nums.reshape(3, 3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [0]:
randoms = torch.rand((3, 3))
randoms

tensor([[0.0688, 0.5091, 0.5668],
        [0.8794, 0.0532, 0.0248],
        [0.1349, 0.1918, 0.1209]])

In [0]:
zeros = torch.zeros((3, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [0]:
ones = torch.ones((3, 3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [0]:
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [0]:
zeros.size()

torch.Size([3, 3])

# Operations

PyTorch로 수학연산

In [0]:
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [0]:
nums = nums.reshape((3, 3))

In [0]:
nums + nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [0]:
result = torch.add(nums, 10)

In [0]:
result.numpy()

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]], dtype=int64)

In [19]:
w = torch.rand(5,3, dtype = torch.float)
x = torch.tensor([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
wx = torch.mm(w,x)
wx.size()

torch.Size([5, 2])

## View

In [0]:
range_nums = torch.arange(9).reshape(3, 3)

In [0]:
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [0]:
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
range_nums.view(1, 9)

torch.Size([1, 9])

# Slice and Index

In [0]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [0]:
nums[1]

tensor([3, 4, 5])

In [0]:
nums[1, 1]

tensor(4)

In [0]:
nums[1:, 1:]

tensor([[4, 5],
        [7, 8]])

In [0]:
nums[1:]

tensor([[3, 4, 5],
        [6, 7, 8]])

## Compile

numpy를 torch tensor로 불러오기

In [0]:
arr = np.array([1, 1, 1])

NameError: ignored

In [0]:
arr_torch = torch.from_numpy(arr)

In [0]:
arr_torch.float()

tensor([1., 1., 1.])

In [0]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [0]:
arr_torch.to(device)

tensor([1, 1, 1], dtype=torch.int32)

In [0]:
device

'cpu'

# AutoGrad

In [0]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [0]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [0]:
print(y.grad_fn)

In [0]:
z = y * y * 3
out = z.mean()

In [0]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [0]:
out.backward()

In [0]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [0]:
print(x.requires_grad)
print((x ** 2).requires_grad)

True
True


In [0]:
with torch.no_grad():
    print((x ** 2).requires_grad)

False


In [0]:
w = torch.tensor(1.0, requires_grad = True) #required_grad = True는 Autograd가 계산할때 w에 대한 미분값을 w.grad에 저장한다.
a = w*3

In [0]:
l = a**2  # l = a제곱 = (3w)제곱 

In [22]:
l.backward()
print('l을 w로 미분한 값은 {}'.format(w.grad))

l을 w로 미분한 값은 18.0
